version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: prod
  versioning-strategy: lockfile-only
  allow:
  - dependency-type: development
