docker-compose-yaml: docker-compose.yml

tasks:
  post-rollout:

    - run:
        name: drush cim
        command: cd web && drush -y cim
        service: cli
    - run:
        name: drush updb
        command: cd web && drush -y updb --cache-clear=0
        service: cli
    - run:
        name: drush cr
        command: cd web && drush -y cr
        service: cli


environments:
  master:
    cronjobs:
      - name: drush cron
        schedule: "*/15 * * * *"
        command: drush cron
        service: cli
    routes:
      - varnish:
        - "drupalmountaincamp.ch"
        - "www.drupalmountaincamp.ch"

