docker-compose-yaml: docker-compose.yml

tasks:
  post-rollout:
    - run:
        name: IF no Drupal installed, then sync database from prod
        command: |
            if [[ ${LAGOON_GIT_SAFE_BRANCH} != "prod" && $(drush core-status bootstrap --pipe) == "" ]]; then
                drush -y sql-sync @lagoon.prod default -v -ddd
            fi
        service: cli
        shell: bash
    - run:
        name: drush updb
        # Sometimes a cache clear is required prior to running database updates.
        # For example, see https://www.drupal.org/project/drupal/issues/2952071
        # Make two database update attempts to workaround this issue.
        command: drush -y updb --cache-clear=0 || (drush cr && drush -y updb --cache-clear=0)
        service: cli
    - run:
        name: drush cr
        command: drush -y cr
        service: cli
    - run:
        name: drush cim
        command: drush -y cim
        service: cli
    - run:
        name: drush cr
        command: drush -y cr
        service: cli

environments:
  prod:
    cronjobs:
      - name: drush cron
        schedule: "*/15 * * * *"
        command: drush cron
        service: cli
    routes:
      - varnish:
        - "drupalmountaincamp.ch"
        - "www.drupalmountaincamp.ch"

